# Generated by Django 4.1.4 on 2022-12-23 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_representative",
            new_name="is_moderator",
        ),
    ]
