# Generated by Django 4.1.4 on 2023-01-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_is_representative_user_is_moderator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="notify_on_new_doc",
        ),
        migrations.RemoveField(
            model_name="user",
            name="notify_on_new_thread",
        ),
        migrations.RemoveField(
            model_name="user",
            name="notify_on_response",
        ),
    ]
