# Generated by Django 5.2 on 2025-09-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_notify_on_new_doc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="user",
            name="netid",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
