# Generated by Django 6.0.4 on 2026-05-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="moderated_courses",
        ),
    ]
