# Generated by Django 6.0.4 on 2026-05-05 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_user_moderated_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="promoted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promoted_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
