# Generated by Django 6.0.4 on 2026-05-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_add_user_promoted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="moderator_welcome_dismissed",
            field=models.BooleanField(default=False),
        ),
    ]
