# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 16:26
from __future__ import unicode_literals

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20151204_1329'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
