# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-01 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160529_1626'),
        ('users', '0009_auto_20161115_1756'),
    ]

    operations = [
    ]
