# Generated by Django 1.9.13 on 2018-03-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20161115_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inferred_faculty',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='inscription_faculty',
            field=models.TextField(blank=True),
        ),
    ]
