# Generated by Django 6.0.5 on 2026-05-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_delete_numeric_netid_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="CasFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("code", models.CharField(max_length=64)),
                ("details", models.TextField(blank=True, default="")),
                ("ticket", models.CharField(blank=True, default="", max_length=512)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
