# Generated by Django 3.2 on 2021-04-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20180325_1317"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_method",
            field=models.CharField(default="ulb-intranet", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="register_method",
            field=models.CharField(default="ulb-intranet", max_length=32),
            preserve_default=False,
        ),
    ]
