# Generated by Django 3.2.5 on 2021-08-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_register_login_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
