# Generated by Django 4.0.1 on 2022-02-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="registration",
        ),
    ]
