# Generated by Django 4.0.1 on 2022-02-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_remove_user_registration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="inferred_faculty",
        ),
        migrations.RemoveField(
            model_name="user",
            name="inscription_faculty",
        ),
        migrations.DeleteModel(
            name="Inscription",
        ),
    ]
