# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='questions.Answer'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'answer')]),
        ),
    ]
