# Generated by Django 6.0.5 on 2026-05-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("document_view", "Vues de documents"),
                            ("document_download", "Téléchargements"),
                            ("search_query", "Recherches"),
                            ("course_page_view", "Vues de cours"),
                            ("login_success", "Connexions"),
                            ("course_follow", "Cours suivis"),
                            ("course_unfollow", "Cours dé-suivis"),
                            ("document_edit", "Éditions de documents"),
                            ("stats_view", "Vues de la page stats"),
                            ("moderation_log_view", "Vues du log de modération"),
                            ("moderation_tree_view", "Vues de l'arbre de modération"),
                            ("upload_submit", "Soumissions d'upload"),
                            ("document_reupload", "Réuploads de documents"),
                            ("my_courses_view", 'Vues de "Mes cours"'),
                            (
                                "moderation_profile_view",
                                "Vues de profils de modérateur·trices",
                            ),
                            ("document_history_view", "Vues d'historique de documents"),
                            (
                                "moderation_about_view",
                                "Vues de la page modération (utilisateurs)",
                            ),
                            (
                                "moderation_about_view_mod",
                                "Vues de la page modération (modérateur·trices)",
                            ),
                            ("finder_view", "Vues du finder"),
                            ("finder_view_deep", "Vues du finder (profondeur ≥ 3)"),
                            (
                                "moderation_manage_view",
                                "Vues de la gestion des modérateur·trices",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "date"], name="stats_daily_name_85da59_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "name"), name="unique_dailystat"
                    )
                ],
            },
        ),
    ]
