version: '3.7'

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: gunicorn www.wsgi:application --bind 0.0.0.0:8000 --timeout 300
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./docker/.env.dev
    depends_on:
      - db
    networks:
      - private
    restart: unless-stopped

  celery:
    image: docker_web
    command: /srv/dochub/ve/bin/celery multi start ${CELERYD_NODES} -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS}
    volumes:
      - media_volume:/home/app/web/media
    env_file:
      - ./docker/.env.celery.dev
    depends_on:
      - web
    networks:
      - private
    restart: unless-stopped

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./docker/.env.dev.db
    networks:
      - private
    restart: unless-stopped

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_dochub-dev.entrypoints=http"
      - "traefik.http.routers.web_dochub-dev.rule=Host(`beta.dochub.be`)"
      - "traefik.http.middlewares.web_dochub-dev-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.web_dochub-dev.middlewares=web_dochub-dev-https-redirect"
      - "traefik.http.routers.web_dochub-dev-secure.entrypoints=https"
      - "traefik.http.routers.web_dochub-dev-secure.rule=Host(`beta.dochub.be`)"
      - "traefik.http.routers.web_dochub-dev-secure.tls=true"
      - "traefik.http.routers.web_dochub-dev-secure.tls.certresolver=http"
      - "traefik.http.routers.web_dochub-dev-secure.service=nginx-dochub-dev@docker"
      - "traefik.docker.network=traefik-proxy"
    depends_on:
      - web
    networks:
      - private
      - public
      - traefik-proxy
    restart: unless-stopped

networks:
  private:
    driver: overlay
  public:
    external: true
  traefik-proxy:
    external: true

volumes:
  postgres_data:
  static_volume:
  media_volume:
