version: '3.7'

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: gunicorn www.wsgi:application --bind 0.0.0.0:8000 --timeout 300
    volumes:
      - static_volume:/srv/collected_static
      - media_volume:/srv/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - private
    restart: unless-stopped

  celery:
    image: dochub-dev_web
    command: celery.sh
    volumes:
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.celery.dev
    depends_on:
      - web
    networks:
      - private
    restart: unless-stopped

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    networks:
      - private
    restart: unless-stopped

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/srv/collected_static
      - media_volume:/srv/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_dochub-dev.entrypoints=http"
      - "traefik.http.routers.web_dochub-dev.rule=Host(`dochub.teamna.me`)"
      - "traefik.http.middlewares.web_dochub-dev-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.web_dochub-dev.middlewares=web_dochub-dev-https-redirect"
      - "traefik.http.routers.web_dochub-dev-secure.entrypoints=https"
      - "traefik.http.routers.web_dochub-dev-secure.rule=Host(`dochub.teamna.me`)"
      - "traefik.http.routers.web_dochub-dev-secure.tls=true"
      - "traefik.http.routers.web_dochub-dev-secure.tls.certresolver=http"
      - "traefik.http.routers.web_dochub-dev-secure.service=nginx-dochub-dev@docker"
      - "traefik.docker.network=traefik-proxy"
    depends_on:
      - web
    networks:
      - private
      - public
      - traefik-proxy
    restart: unless-stopped

networks:
  private:
    driver: overlay
  public:
    external: true
  traefik-proxy:
    external: true

volumes:
  postgres_data:
  static_volume:
  media_volume:
