# Generated by Django 4.1.1 on 2022-10-12 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0001_initial"),
        ("catalog", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Titre")),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("edited", models.DateTimeField(auto_now=True)),
                ("size", models.PositiveIntegerField(default=0)),
                ("pages", models.PositiveIntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("file_type", models.CharField(default="", max_length=255)),
                ("original", models.FileField(upload_to="original_document")),
                ("pdf", models.FileField(upload_to="pdf_document")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PREPARING", "En préparation"),
                            ("READY_TO_QUEUE", "Prêt à être ajouté à Celery"),
                            ("IN_QUEUE", "Envoyé à Celery"),
                            ("PROCESSING", "En cours de traitement"),
                            ("DONE", "Rendu fini"),
                            ("ERROR", "Erreur"),
                            ("REPAIRED", "Réparé"),
                        ],
                        db_index=True,
                        default="PREPARING",
                        max_length=20,
                        verbose_name="État",
                    ),
                ),
                ("md5", models.CharField(db_index=True, default="", max_length=32)),
                (
                    "hidden",
                    models.BooleanField(default=False, verbose_name="Est caché"),
                ),
                (
                    "import_source",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Importé depuis",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.course",
                        verbose_name="Cours",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="tags.tag")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentError",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255)),
                ("exception", models.CharField(max_length=50000)),
                ("traceback", models.TextField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField(auto_now=True)),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("up", "Upvote"), ("down", "Downvote")], max_length=10
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "document")},
            },
        ),
    ]
