# Generated by Django 4.1.4 on 2023-01-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="certified",
            field=models.BooleanField(default=False, verbose_name="Est certifié"),
        ),
    ]
