# Generated by Django 4.2 on 2023-06-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_document_staff_pick"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="thumbnail",
            field=models.FileField(null=True, upload_to="thumbnail"),
        ),
    ]
