# Generated by Django 4.2.3 on 2023-09-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_document_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="migrated_from_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="migrated_from_slug",
            field=models.CharField(null=True),
        ),
    ]
