# Generated by Django 6.0 on 2025-12-24 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0005_alter_vote_unique_together_alter_bulkdocuments_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_type",
                    models.CharField(
                        choices=[
                            ("wrong_module", "Ce document est dans le mauvais cours"),
                            ("wrong_title", "Le titre ou la description est erroné"),
                            ("low_quality", "Contenu de mauvaise qualité ou inutile"),
                            ("readability", "Problème de lisibilité"),
                            ("other", "Autre raison"),
                        ],
                        max_length=20,
                        verbose_name="Type de problème",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["document", "created"],
                        name="documents_d_documen_38f1e0_idx",
                    ),
                    models.Index(
                        fields=["created"], name="documents_d_created_21a40d_idx"
                    ),
                ],
            },
        ),
    ]
