# Generated by Django 6.0 on 2025-12-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_documentreport"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documentreport",
            name="documents_d_documen_38f1e0_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentreport",
            name="documents_d_created_21a40d_idx",
        ),
        migrations.AlterField(
            model_name="documentreport",
            name="problem_type",
            field=models.CharField(
                choices=[
                    ("wrong_module", "Ce document est dans le mauvais cours"),
                    ("wrong_title", "Le titre ou la description est erroné"),
                    ("low_quality", "Contenu de mauvaise qualité ou inutile"),
                    ("readability", "Problème de lisibilité"),
                    ("outdated", "Document obsolète"),
                    ("other", "Autre raison"),
                ],
                max_length=20,
                verbose_name="Type de problème",
            ),
        ),
    ]
