# Generated by Django 6.0.7 on 2026-09-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_documentreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentreport",
            name="problem_type",
            field=models.CharField(
                choices=[
                    ("wrong_module", "Ce document est dans le mauvais cours"),
                    ("wrong_title", "Le titre ou la description est erroné"),
                    ("low_quality", "Contenu de mauvaise qualité ou inutile"),
                    ("readability", "Problème de lisibilité"),
                    ("outdated", "Le document n'est plus à jour"),
                    ("other", "Autre raison"),
                ],
                max_length=20,
                verbose_name="Type de problème",
            ),
        ),
    ]
