# Generated by Django 1.9.13 on 2018-03-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_auto_20180104_0009"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="document",
        ),
        migrations.DeleteModel(
            name="Page",
        ),
    ]
