# Generated by Django 1.9.13 on 2018-03-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_auto_20180222_1513"),
        ("documents", "0009_auto_20180305_1621"),
    ]

    operations = []
