# Generated by Django 2.0.13 on 2021-02-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_document_import_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenterror",
            name="exception",
            field=models.CharField(max_length=50000),
        ),
    ]
