# Generated by Django 4.0.2 on 2022-02-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_auto_20210203_1828"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_certified",
            field=models.BooleanField(default=False),
        ),
    ]
