# Generated by Django 4.0.1 on 2022-02-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_auto_20210203_1828"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="import_source",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Importé depuis"
            ),
        ),
    ]
