# Generated by Django 4.2.1 on 2023-05-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="icon",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
