# Generated by Django 4.1.4 on 2023-01-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representativerequest",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Commentaires"),
        ),
        migrations.AlterField(
            model_name="representativerequest",
            name="faculty",
            field=models.CharField(
                choices=[
                    ("droit", "Droit"),
                    ("medecine", "Médecine"),
                    ("motricite", "Motricité"),
                    ("pharma", "Pharmacie"),
                    ("philo", "Philosophie et Sciences Sociales"),
                    ("polytech", "Polytech"),
                    ("sciences", "Sciences"),
                    ("solvay", "Solvay"),
                    ("other", "Autre"),
                ],
                max_length=255,
                verbose_name="Faculté",
            ),
        ),
        migrations.AlterField(
            model_name="representativerequest",
            name="role",
            field=models.CharField(
                choices=[
                    ("course", "Délégué cours du cercle"),
                    ("bureau", "Membre du bureau étudiant"),
                    ("delegate", "Délégué d'année"),
                    ("motivated", "Étudiant motivé"),
                    ("other", "Autre"),
                ],
                max_length=255,
            ),
        ),
    ]
