# Generated by Django 6.0 on 2026-04-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0003_moderationlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="representativerequest",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Raison du refus"),
        ),
    ]
