# Generated by Django 6.0 on 2026-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0004_representativerequest_rejection_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representativerequest",
            name="rejection_reason",
            field=models.TextField(
                blank=True, default="", verbose_name="Raison du refus"
            ),
        ),
    ]
