# Generated by Django 6.1.1 on 2026-10-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderation", "0005_alter_representativerequest_rejection_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representativerequest",
            name="role",
            field=models.CharField(
                choices=[
                    ("course", "Délégué·e cours du cercle"),
                    ("bureau", "Membre du bureau étudiant"),
                    ("delegate", "Délégué·e d'année"),
                    ("motivated", "Étudiant·e motivé·e"),
                    ("other", "Autre"),
                ],
                max_length=255,
            ),
        ),
    ]
