# Generated by Django 4.1.1 on 2022-10-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BA", "Bachelier"),
                            ("MA", "Master"),
                            ("MS", "Master de spécialisation"),
                            ("CERT", "Certificat"),
                            ("AGG", "Agrégation"),
                            ("UNI", "Université"),
                            ("FAC", "Faculté"),
                            ("BLOC", "Bloc"),
                        ],
                        default=None,
                        max_length=4,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(default="")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("Q1", "1er quadri"),
                            ("Q2", "2ème quadri"),
                            ("Y", "Toute l'année"),
                            ("?", "Inconnu"),
                        ],
                        default="?",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mandatory", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseUserView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.IntegerField(default=1)),
                ("last_view", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.course"
                    ),
                ),
            ],
        ),
    ]
