# Generated by Django 4.1.1 on 2022-10-12 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courseuserview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.category"
            ),
        ),
        migrations.AddField(
            model_name="coursecategory",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.course"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(
                through="catalog.CourseCategory", to="catalog.category"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="followed_by",
            field=models.ManyToManyField(
                related_name="courses_set", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parents",
            field=models.ManyToManyField(
                blank=True, related_name="children", to="catalog.category"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseuserview",
            unique_together={("user", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="coursecategory",
            unique_together={("course", "category")},
        ),
    ]
