# Generated by Django 4.2.3 on 2023-09-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
    ]
