# Generated by Django 6.0 on 2025-12-21 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_category_is_archive_course_is_archive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coursecategory",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="courseuserview",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="courseuserview",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecategory",
            constraint=models.UniqueConstraint(
                fields=("course", "category"), name="unique_course_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseuserview",
            constraint=models.UniqueConstraint(
                fields=("user", "course"), name="unique_user_course_view"
            ),
        ),
    ]
