# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-01 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_course_description'),
        ('catalog', '0004_auto_20161007_1309'),
    ]

    operations = [
    ]
