# Generated by Django 6.0.7 on 2026-08-17 12:28

from django.db import migrations, models


def unknown_period_to_null(apps, schema_editor):
    Course = apps.get_model("catalog", "Course")
    Course.objects.filter(period="?").update(period=None)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_coursecategory_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Q1", "1er quadri"),
                    ("Q2", "2ème quadri"),
                    ("Y", "Toute l'année"),
                ],
                default=None,
                max_length=4,
                null=True,
            ),
        ),
        migrations.RunPython(unknown_period_to_null, migrations.RunPython.noop),
    ]
