# Generated by Django 3.2.5 on 2021-08-03 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0005_auto_20210104_2213"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="followed_by",
            field=models.ManyToManyField(
                related_name="courses_set", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
