# Generated by Django 3.2.5 on 2021-08-07 20:25

from django.db import migrations, models

from catalog.slug import Slug


def forwards(apps, schema_editor):
    Course = apps.get_model("catalog", "Course")
    for course in Course.objects.all():
        raw_slug = course.slug

        if raw_slug.lower().startswith("iinfo"):
            raw_slug = raw_slug[1:]

        slug = Slug.match_all(raw_slug)
        course.slug = slug.dochub
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_category_slug"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
