# Generated by Django 4.0.4 on 2022-05-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_normalize_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[
                    ("BA", "Bachelier"),
                    ("MA", "Master"),
                    ("CERT", "Certificat"),
                    ("AGG", "Agrégation"),
                    ("OTHE", "Autre"),
                ],
                default="OTHE",
                max_length=4,
            ),
        ),
    ]
