# Generated by Django 6.0.7 on 2026-09-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_require_category_edition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[
                    ("BA", "Bachelier"),
                    ("MA", "Master"),
                    ("TEAC", "Master en enseignement"),
                    ("MS", "Master de spécialisation"),
                    ("CERT", "Certificat"),
                    ("AGG", "Agrégation"),
                    ("UNI", "Université"),
                    ("FAC", "Faculté"),
                    ("BLOC", "Bloc"),
                ],
                default=None,
                max_length=4,
                null=True,
            ),
        ),
    ]
