# Generated by Django 4.0.4 on 2022-05-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_coursecategory_mandatory_and_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="period",
            field=models.CharField(
                choices=[
                    ("Q1", "1er quadri"),
                    ("Q2", "2ème quadri"),
                    ("Y", "Toute l'année"),
                    ("?", "Inconnu"),
                ],
                default="?",
                max_length=4,
            ),
        ),
    ]
