# Generated by Django 4.0.4 on 2022-05-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_unique_category_slug"),
    ]

    def forwards(apps, schema_editor):
        Category = apps.get_model("catalog", "Category")
        for cat in Category.objects.all():
            if cat.parent:
                cat.parents.add(cat.parent)

    def backwards(apps, schema_editor):
        Category = apps.get_model("catalog", "Category")
        for cat in Category.objects.all():
            cat.parents.clear()

    operations = [
        migrations.AddField(
            model_name="category",
            name="parents",
            field=models.ManyToManyField(
                blank=True, related_name="children", to="catalog.category"
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="category",
            name="level",
        ),
        migrations.RemoveField(
            model_name="category",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="category",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="category",
            name="tree_id",
        ),
    ]
