# Generated by Django 4.0.4 on 2022-06-02 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0015_remove_mptt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[
                    ("BA", "Bachelier"),
                    ("MA", "Master"),
                    ("MS", "Master de spécialisation"),
                    ("CERT", "Certificat"),
                    ("AGG", "Agrégation"),
                    ("UNI", "Université"),
                    ("FAC", "Faculté"),
                    ("BLOC", "Bloc"),
                ],
                default=None,
                max_length=4,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CourseUserView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.IntegerField(default=1)),
                ("last_view", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "course")},
            },
        ),
    ]
